### ISSUE TITLE
NinjaCoder.Wpf.Zip Misspelled 

### ISSUE THREAD

**Issue by benhysell** [asudbury/Ninja4MvxInstaller#1]
https://github.com/asudbury/Ninja4MvxInstaller/blob/c409e8ef8dd30f5666fcb7139368637db5a1725e/ProjectTemplates2013.wxs#L17

Causes the WPF project template to fail.

Output log 

WebAuthentication.Client.Core project successfully added. (template MvvmCross.Core.zip)
WebAuthentication.Client.Core.Tests project successfully added. (template NinjaCoder.MSTest.zip)
ERROR WebAuthentication.Client.Wpf not added. exception The system cannot find the file specified. (Exception from HRESULT: 0x80070002) (template NinjaCoder.Wpf.zip)
MainViewModel.cs added to WebAuthentication.Client.Core project (template=MvvmCross.ViewModel.SampleData.zip)
TestMainViewModel.cs added to WebAuthentication.Client.Core.Tests project (template=MvvmCross.MSTest.TestViewModel.SampleData.zip)

Attempted to fix the spelling of the zip file in:

C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\ProjectTemplates\CSharp\Ninja Coder

And re-run the solution create, however it still failed.

**Comment by benhysell** [comment]
Turned on the log this morning to see if there was anything else in there...not excatly sure what is going on there, this is after I found the template in C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\ProjectTemplates\CSharp\Ninja Coder and renamed it to be the proper name.

27 Feb 15 08:42:48 001  ProjectsService::AddProjects
27 Feb 15 08:42:48 004  ProjectsService::AddProjects project count=3 path=C:\Jobs\DataCollector\Trunk\Software\Sandbox\WebAuthentication\WebAuthentication.Client
27 Feb 15 08:42:48 008  ProjectsService::AddProjectIf project WebAuthentication.Client.Core
27 Feb 15 08:42:48 011  ProjectsService::TryToAddProject  project=WebAuthentication.Client.Core
27 Feb 15 08:42:48 015  ProjectsService::AddProjectIf project=WebAuthentication.Client.Core templateName=MvvmCross.Core.zip
27 Feb 15 08:42:48 018  SolutionExtensions::GetProjectTemplate templateName=MvvmCross.Core.zip
27 Feb 15 08:42:48 177  Template=C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\ProjectTemplatesCache\CSharp\Ninja Coder\MvvmCross\MvvmCross.Core.zip\MvvmCross.Core.vstemplate
27 Feb 15 08:42:48 180  SolutionExtensions::AddProjectToSolution path=C:\Jobs\DataCollector\Trunk\Software\Sandbox\WebAuthentication\WebAuthentication.Client\WebAuthentication.Client.Core\
27 Feb 15 08:42:54 575  ProjectsService::AddProjectIf project WebAuthentication.Client.Core.Tests
27 Feb 15 08:42:54 580  ProjectsService::TryToAddProject  project=WebAuthentication.Client.Core.Tests
27 Feb 15 08:42:54 585  ProjectsService::AddProjectIf project=WebAuthentication.Client.Core.Tests templateName=NinjaCoder.MSTest.zip
27 Feb 15 08:42:54 599  SolutionExtensions::GetProjectTemplate templateName=NinjaCoder.MSTest.zip
27 Feb 15 08:42:54 609  Template=C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\ProjectTemplatesCache\CSharp\Ninja Coder\NinjaCoder.MSTest.zip\NinjaCoder.MSTest.vstemplate
27 Feb 15 08:42:54 613  SolutionExtensions::AddProjectToSolution path=C:\Jobs\DataCollector\Trunk\Software\Sandbox\WebAuthentication\WebAuthentication.Client\WebAuthentication.Client.Core.Tests\
27 Feb 15 08:42:55 638  ProjectExtensions::AddProjectReference project=WebAuthentication.Client.Core.Tests
27 Feb 15 08:42:55 823  ProjectsService::AddProjectIf project WebAuthentication.Client.Wpf
27 Feb 15 08:42:55 827  ProjectsService::TryToAddProject  project=WebAuthentication.Client.Wpf
27 Feb 15 08:42:55 829  ProjectsService::AddProjectIf project=WebAuthentication.Client.Wpf templateName=NinjaCoder.Wpf.zip
27 Feb 15 08:42:55 833  SolutionExtensions::GetProjectTemplate templateName=NinjaCoder.Wpf.zip
27 Feb 15 08:42:55 842  --------------------------------------------------------
27 Feb 15 08:42:55 845 ** ERROR ** error adding project C:\Jobs\DataCollector\Trunk\Software\Sandbox\WebAuthentication\WebAuthentication.Client\WebAuthentication.Client.Wpf\ exception=The system cannot find the file specified. (Exception from HRESULT: 0x80070002) templateName=NinjaCoder.Wpf.zip
27 Feb 15 08:43:18 908  --------------------------------------------------------
27 Feb 15 08:43:18 913  ProjectsController::FixInfoPlist
27 Feb 15 08:43:18 941  ViewModelAndViewsFactory::GetRequiredViewModelAndViews
27 Feb 15 08:43:18 947  ViewModelViewsService::AddViewModelAndViews
27 Feb 15 08:43:18 952  SolutionExtensions::AddItemTemplateToProjects

**Comment by asudbury** [comment]
fixed with version 4.0.0 of ninja coder.
